name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Specify Node.js 20

      - name: Build
        run: npm run build
        env:
          SECRET_KEY: ${{ secrets.SENDER_EMAIL_TOKEN }}  # Referencing the secret here

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # Adjust the path if your HTML files are in a subdirectory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: ./
